name: CI-Test

on:
  push:
    branches:
      - development

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [raspbian-latest]
        python-version: ["3.9"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest .
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Commit to testing branch
        run: |
          git checkout -b testing
          git add .
          git commit -m "Automated testing commit"
          git push origin testing
