name: CI-Main

on:
  push:
    branches:
      - main

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: git config --global user.email "github-actions@github.com" && git config --global user.name "GitHub Actions"

      - name: Manual commit to main
        run: |
          git checkout main
          # Perform any manual steps or adjustments if needed
          git add .
          git commit -m "Manual commit to main"
          git push origin main
          git push origin main
