name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure Buildx
        run: docker buildx create --driver=docker-container --name=multi --use

      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/project-52_pi:latest --progress plain --platform linux/amd64,linux/arm64 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/project-52_pi:latest
