name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          KEYS_CFG_CONTENTS: ${{ secrets.KEYS_CFG_CONTENTS }}
        run: |
          echo "$KEYS_CFG_CONTENTS" > Keys.cfg
          docker buildx create --use
          docker buildx build --platform linux/arm/v8 -t ${{ secrets.DOCKER_USERNAME }}/project-52_pi:latest --push --no-cache .

