name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Set this to the label of your Raspberry Pi runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull  ${{ secrets.DOCKER_USERNAME }/Project-52_Pi:tag

      - name: Run Docker container
        run: docker run -d  ${{ secrets.DOCKER_USERNAME }/Project-52_Pi:tag
